apiVersion: v1
kind: Pod
metadata:
  name: hello-world-affinity
spec:
  containers:
    - name: hello-world
      image: your-dockerhub-username/hello-world-node:latest
      ports:
        - containerPort: 8080
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                  - your-target-node-name
  tolerations:
    - key: "env"
      operator: "Equal"
      value: "dev"
      effect: "NoSchedule"
apiVersion: v1
kind: Pod
metadata:
  name: hello-world-affinity
spec:
  containers:
    - name: hello-world
      image: shreyaawasthi/hello-node-app:day1
      ports:
        - containerPort: 8080
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                  - minikube
  tolerations:
    - key: "env"
      operator: "Equal"
      value: "dev"
      effect: "NoSchedule"
